# Generated by Django 6.0 on 2025-12-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistri_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistri',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mistri',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mistri',
            name='skill',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
